spring:
  application:
    name: controle-horas
  datasource:
    url: jdbc:mysql://35.198.58.59:3306/tarefas
    username: chronosapi
    password: Bolsonaro#22
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
