spring.application.name=controle-horas

#conexão
spring.datasource.url=jdbc:mysql://35.199.95.124:3306/gsw_database
spring.datasource.username=chronosapi
spring.datasource.password=Bolsonaro#22

#comando
spring.jpa.hibernate.ddl-auto=update

server.port=8082

#spring.data.redis.host=${REDIS_HOST:redis-cache}
#spring.data.redis.port=${REDIS_PORT:6379}